### ISSUE TITLE
npm install gives fsevents errors

### ISSUE THREAD

**Issue by ykcadcg** [IBM/build-react-native-app-for-watson-discovery#26]
I'm following steps and am at "Step 4" npm install, got a lot errors around
`In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:223:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/conanyang/Library/Caches/node-gyp/12.14.0/include/node/v8.h:5426:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
`
and a lot of errors around
`../fsevents.cc:76:16: error: variable has incomplete type 'void'
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
               ^
`

Could you help me successfully launch the app? Thanks!

**Comment by ykcadcg** [comment]
Shall we update package.json/ package-lock.json? How?

**Comment by tmarkiewicz** [comment]
@ykcadcg I'm unable to replicate. I followed the steps through four as well on a Mac OS X (v10.14.6) laptop with the following versions and had no errors running `npm install`:

node v12.11.1
npm 6.11.3

Could you post what you're running?
